### ISSUE TITLE
Change the pattern

### ISSUE THREAD

**Issue by digitil** [buildium/password-strength#3]
How do we feel about implementing a builder pattern for constructing the password strength checker?
This would give the client the advantage of being able to more easily tailor the checker.
An example of what this would look like is

```
    var checkPassword = bdPasswordStrength
        .withNumCharacters({weight: 4})
        .withUpperCaseLetters(false)
        .withMiddleNumbersAndSymbols({weight: 5})
        .build();
```

and provided flavors like

```
var checkPassword = bdPasswordStrength.lettersNumbersSpecialChars();
// or
var checkPassword = bdPasswordStrength.letters().numbers().specialChars();
```

**Comment by jbalboni** [comment]
That seems nice.

**Comment by benmj** [comment]
I'm fascinated by this approach, partially because I've never tried it before!

@digitil do you have interest in taking a crack at a basic implementation?

**Comment by Doelfke** [comment]
I stared this: https://github.com/buildium/password-strength/pull/8
